config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'sessions#new'

  get 'register', to: 'users#new'
  resources :users, only: [:create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'backlog/list', to: 'tasks#index'
  resources :tasks, only: %i[create update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/decorations/tasks.rb
# frozen_string_literal: true

module Decorations::Tasks
  extend ActiveSupport::Concern

  def state_action
    I18n.t "task.state_action.#{state}"
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include Decorations::Tasks
  WEIGHTED_PRIORITY = { 5 => 'important', 10 => 'urgent' }.freeze
  STATES_CYCLE = { 'open' => 'process', 'process' => 'closed' }.freeze

  DESCRIPTION_MAX_LENGTH = 40
  DESCRIPTION_MIN_LENGTH = 1

  belongs_to :user

  validates_length_of :description, maximum: DESCRIPTION_MAX_LENGTH, minimum: DESCRIPTION_MIN_LENGTH

  def closed?
    state == 'closed'
  end

  def pivot_to_next_state!
    return unless STATES_CYCLE[state]
    self.state = STATES_CYCLE[state]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  USERNAME_MAX_LENGTH = 16
  USERNAME_MIN_LENGTH = 4

  PASSWORD_MAX_LENGTH = 16
  PASSWORD_MIN_LENGTH = 8

  has_secure_password
  validates_uniqueness_of :username
  validates_length_of :username, maximum: USERNAME_MAX_LENGTH, minimum: USERNAME_MIN_LENGTH
  validates_length_of :password, maximum: PASSWORD_MAX_LENGTH, minimum: PASSWORD_MIN_LENGTH
  validate :username_legibility, :password_legibility, on: %i[create update]

  has_many :tasks, dependent: :destroy

  def username_legibility
    errors.add(:username, "can't use special charaters") if /\W+/.match?(username)
  end

  def password_legibility
    errors.add(:password, 'should contains at least 1 upper case, 1 lower case, 1 number') unless legal_password
  end

  private

  def legal_password
    /\d+/.match?(password) && /[A-Z]+/.match?(password) && /[a-z]+/.match?(password)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @_current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create]
  before_action :already_login?, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: user_params[:username])
    if @user&.authenticate(user_params[:password])
      flash[:success] = "Hi, #{@user.username}, nice to see you again~"
      session[:user_id] = @user.id
      redirect_to backlog_list_path
    else
      @user = User.new(username: user_params[:username])
      flash.now[:danger] = 'User does not exist or the password is not correct'
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end

  private

  def already_login?
    return unless logged_in?

    flash[:warning] = 'Alreadt Logged In.'
    redirect_to backlog_list_path
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :load_and_check_current_task, only: %i[update destroy]

  def index
    @tasks = current_user.tasks.order("state = 'process' DESC, state = 'open' DESC, state = 'closed' DESC")
  end

  def create
    @task = current_user.tasks.new(task_params.to_hash)
    if @task.save
      flash.now[:success] = 'Added a new task'
    else
      flash.now[:danger] = @task.errors.full_messages.join('<br/>')
      render 'shared/show_flash_notice'
    end
  end

  def update
    @task.pivot_to_next_state!
    if @task.save
      flash.now[:success] = 'Changed the task state'
    else
      flash.now[:danger] = @task.errors.full_messages.join('<br/>')
      render 'shared/show_flash_notice'
    end
  end

  def destroy
    flash.now[:success] = 'Removed the task'
    @task.delete
  end

  private

  def task_params
    params.require(:task).permit(:description, priorities: {}).tap do |p|
      p[:priorities] = p[:priorities].values.map(&:to_i).select(&:positive?)
    end
  end

  def load_and_check_current_task
    @task = current_user.tasks.find_by(id: params[:id])
    return render file: "#{Rails.root}/public/422.html" unless @task
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(username: user_params[:username], password: user_params[:password], password_confirmation: user_params[:password_confirm])
    if @user.save
      flash[:success] = 'Created an account welcome to use our product.'
      session[:user_id] = @user.id
      redirect_to backlog_list_path
    else
      flash.now[:danger] = @user.errors.full_messages.join('<br/>')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirm)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def show_closed_tasks?
    cookies['showClosedTask'] == 'true'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/header' if logged_in? %>
    <section>
      <%= render 'shared/messages' %>
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_header.erb
<div class='nav bg-light align-items-center'>
  <h2 class='p-3 flex-grow-1'>Backlog</h2>
  <div class='pr-3'>Hi, <%= current_user.username %></div>
  <%= link_to  "Logout", logout_path, remote: true, method: :delete, class: 'mr-4 btn btn-light border' %>
</div>

app/views/shared/_messages.html.erb
<%- flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
    <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_show_flash_notice.js.erb
$('body section .alert-dismissible').remove()
$('body section').prepend('<%= j render 'shared/messages' %>')

app/views/shared/_user_form.erb
<%-
  register = local_assigns.fetch :register, nil
%>

<div class="container mt-3">
  <div class="d-flex justify-content-center h-100">
    <%= form_for @user, url: register ? users_path : login_path do |f| %>
      <div class="input-group form-group">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-user"></i></span>
        </div>
        <%= f.text_field :username, class: "form-control", placeholder: 'username' %>
      </div>

      <div class="input-group form-group">
        <div class="input-group-prepend">
          <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <%= f.password_field :password, class: "form-control", placeholder: 'password' %>
      </div>
      <%- if register %>
        <div class="input-group form-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
          </div>
          <%= f.password_field :password_confirm, class: "form-control", placeholder: 'password' %>
        </div>
      <% end %>

      <div class="form-group d-flex justify-content-between">
        <%= link_to register ? 'login' : 'register', register ? login_path : register_path, class: 'btn btn-outline-primary' %>
        <%= f.submit register ? 'register' : 'login', class: 'btn btn-outline-dark' %>
      </div>      
    <% end %>
  </div>
</div>

app/views/tasks/_priority_buttons.erb
<%- Task::WEIGHTED_PRIORITY.each do |weight, priority| %>
  <label class="col">
    <%= radio_button_tag "task[priorities][#{priority}]", '', true, class: 'default' %>
    Not <%= priority.capitalize %>
  </label>
  <label class="col">
    <%= radio_button_tag "task[priorities][#{priority}]", weight %>
    <%= priority.capitalize %>
  </label>
<% end %>

app/views/tasks/_task.erb
<div class="list-group-item list-group-item-action align-items-center <%= task.state %> <%= (task.closed? && !show_closed_tasks?) ? 'd-none' : 'd-flex'%>">
  <div class='flex-grow-1'>
    <span><%= task.description %></span>
    <span class="badge badge-<%= task.state %>"><%= task.state %></span>
  </div>

  <div>
    <%- task.priorities.each do |priority| %>
      <span class="mr-1 badge badge-<%= Task::WEIGHTED_PRIORITY[priority] %>"><%= Task::WEIGHTED_PRIORITY[priority] %></span>
    <% end %>
  </div>

  <%= link_to_if !task.closed?, task.state_action, task, class: 'btn btn-primary mx-2', remote: true, method: :patch %>

  <%= link_to task, remote: true, method: :delete do %>
    <button type="button" class="close ml-1" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  <% end %>
</div>

app/views/tasks/_tasks.erb
<div class="tasks">  
  <%- @tasks&.each do |task| %>
    <%= render 'task', task: task %>
  <% end %>
</div>

app/views/tasks/create.js.erb
$('.tasks-list .list-group .tasks').append('<%= j render 'task', task: @task %>')
$('#task_description').val('')
$('input.default').click()
<%= render 'shared/show_flash_notice.js' %>

app/views/tasks/destroy.js.erb
$('a[href="<%= task_path(@task) %>"]').parent('.list-group-item').remove()
$('body section').prepend('<%= j render 'shared/messages' %>')
<%= render 'shared/show_flash_notice.js' %>

app/views/tasks/index.html.erb
<div class='list tasks-list'>
  <div class='w-75 mx-auto mt-5'>
    <div class="list-group">
      <div class="bg-info d-flex align-items-center">
        <h3 class='p-2 my-0 mx-3 text-light flex-grow-1'>Tasks</h3>
        <div class='d-flex align-items-center mr-3'>
          <%= label_tag :show_closed do %>
            <%= check_box_tag :show_closed, nil, show_closed_tasks? %>
            <span class='text-white font-weight-bold'>show closes tasks</span>
          <% end %>
        </div>
      </div>
      <%= render 'tasks' %>
    </div>

    <%= form_for Task.new, remote: true, html: { class: 'd-flex align-items-end mt-5' } do |f| %>
      <div class='w-100'>
        <label for="basic-url">Enter your task</label>
        <%= f.text_field :description, placeholder: 'description', class: 'form-control' %>
      </div>

      <%= f.submit 'ADD', class: 'btn btn-primary mx-3', data: { "disable-with": "Add..." } %>

      <div class="row row-cols-<%= Task::WEIGHTED_PRIORITY.count %>">
        <%= render 'priority_buttons' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/update.js.erb
$('a[href="<%= task_path(@task) %>"]').parent('.list-group-item').remove()
<%- if @task.closed? %>
  $('.tasks-list .list-group .tasks').append('<%= j render 'task', task: @task %>')
<% else %>
  $('.tasks-list .list-group .tasks').prepend('<%= j render 'task', task: @task %>')
<% end %>
<%= render 'shared/show_flash_notice.js' %>

app/views/users/new.html.erb
<%= render 'shared/user_form', register: true %>